---
- hosts:         localhost
  remote_user:   root
  become:        yes
  become_method: sudo
  tasks:
  - name:    Install terminal apps
    include: terminal_{{ dist }}.yml
  - name:    Install GUI apps and vitamins
    include: gui_apps_{{ dist }}.yml

