---
- name:   Ensure Android Studio installed
  aur:    user="{{ user }}" name=android-studio
- name:   Ensure Chrome installed
  aur:    user="{{ user }}" name=google-chrome
- pacman: state=present     name=chrome-gnome-shell
- name:   Ensure Clementine installed
  pacman: state=present     name=clementine
- name:   Ensure Conky installed
  pacman: state=present     name=conky
- pacman: state=present     name=conky-manager
- name:   Ensure Dropbox installed
  pacman: state=present     name=dropbox
- aur:    user="{{ user }}" name=nautilus-dropbox
- name:   Ensure Double Commander installed
  pacman: state=present     name=doublecmd-gtk2
- name:   Ensure Franz installed
  aur:    user="{{ user }}" name=franz-bin
- name:   Ensure Fira Code installed
  aur:    user="{{ user }}" name=fira-code-git
- name:   Ensure Firefox installed
  pacman: state=present     name=firefox
- name:   Ensure Hyper installed
  aur:    user="{{ user }}" name=hyper
- name:   Ensure IntelliJ Idea CE installed
  pacman: state=present     name=intellij-idea-community-edition
- name:   Ensure KeePass installed
  pacman: state=present     name=keepass
- aur:    user="{{ user }}" name=keepass-plugin-http
- name:   Ensure Nylas Mail installed
  aur:    user="{{ user }}" name=nylas-mail-bin
- name:   Ensure Paper theme installed
  aur:    user="{{ user }}" name=paper-gtk-theme-git
- name:   Ensure PgAdmin3 installed
  pacman: state=present     name=pgadmin3
- aur:    user="{{ user }}" name=paper-icon-theme-git
- name:   Ensure Spotify installed
  aur:    user="{{ user }}" name=spotify
- aur:    user="{{ user }}" name=ffmpeg0.10
- aur:    user="{{ user }}" name=zenity
- name:   Ensure Source Code Pro installed
  pacman: state=present     name=adobe-source-code-pro-fonts
- name:   Ensure Sublime Text 3 installed
  aur:    user="{{ user }}" name=sublime-text-nightly
- name:   Ensure Thunderbird installed
  pacman: state=present     name=thunderbird
