---
- name:   Ensure amm installed
  aur:    user="{{ user }}" name=ammonite
- name:   Ensure clojure installed
  pacman: state=present     name=clojure
- name:   Ensure CLOC installed
  pacman: state=present     name=cloc
- name:   Ensure Docker installed
  pacman: state=present     name=docker
- pacman: state=present     name=docker-compose
- pacman: state=present     name=docker-machine
- name:   Ensure Emacs installed
  pacman: state=present     name=emacs
- name:   Ensure Git installed
  pacman: state=present     name=git
- pacman: state=present     name=git-repair
- name:   Ensure Gradle installed
  pacman: state=present     name=gradle
- name:   Ensure htop installed
  pacman: state=present     name=htop
- name:   Ensure JDK8 installed
  pacman: state=present     name=jdk8-openjdk
- shell:  "archlinux-java set java-8-openjdk"
- name:   Ensure midnight commander installed
  pacman: state=present     name=mc
- name:   Ensure micro installed
  pacman: state=present     name=micro-bin
- name:   Ensure neovim installed
  pacman: state=present     name=neovim
- name:   Ensure PIP installed
  pacman: state=present     name=python-pip
- pacman: state=present     name=python2-pip
- name:   Ensure SBT installed
  pacman: state=present     name=sbt
- name:   Ensure RVM installed
  shell:  "gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3"
- shell:  "{{ playbook_dir }}/scripts/rvm-installer.sh stable --auto-dotfiles"
- name:   Ensure stack installed
  pacman: state=present     name=stack
- name:   Ensure tmux installed
  pacman: state=present     name=tmux
- name:   Ensure Vim installed
  pacman: state=present     name=vim
- name:   Ensure zsh installed
  pacman: state=present     name=zsh
